name: sqlitebrowser  # the name of the snap
version: 0.1  # the version of the snap
summary: DB browser for Sqlite  # 79 char long summary
description: GUI editor for SQLite databases  # a longer description for the snap
confinement: devmode  # use "strict" to enforce system access only via declared interfaces

grade: devel
confinement:        devmode
icon:               snap/sqlitebrowser.svg
type:               app

apps:
  sqlitebrowser:
    command: desktop-launch $SNAP/bin/sqlitebrowser
    desktop: share/applications/sqlitebrowser.desktop

build-packages:
    - build-essential
    - g++
    - qtbase5-dev
    - qttools5-dev
    - qttools5-dev-tools
    - libsqlite3-dev
    - cmake
    - libantlr-dev
    - libqcustomplot-dev
parts:
    sqlitebrowser:  # Replace with a part name of your liking
        # Get more information about plugins by running
        # snapcraft help plugins
        # and more information about the available plugins
        # by running
        # snapcraft list-plugins plugin autotools
        source-type: git
        plugin: cmake
        source: https://github.com/sqlitebrowser/sqlitebrowser.git

    dump:  # Replace with a part name of your liking
        # Get more information about plugins by running
        # snapcraft help plugins
        # and more information about the available plugins
        # by running
        # snapcraft list-plugins plugin autotools
        plugin: dump
        after:
        - sqlitebrowser
        stage-packages:
        - qtbase5-dev
        - qttools5-dev
        - qttools5-dev-tools
        - libsqlite3-dev
        - libantlr-dev
        - libqcustomplot-dev
        - libx11-xcb1
        - libx11-xcb-dev
        - libxcb-icccm4-dev
        - libxcb-image0-dev
        - libxcb-keysyms1-dev
        - libxcb-randr0-dev
        - libxcb-render-util0-dev
        - libxcb-render0-dev
        - libxcb-shape0-dev
        - libxcb-shm0-dev
        - libxcb-sync-dev
        - libxcb-xfixes0-dev
        - libxcb-xinerama0-dev
        - libxcb-xkb-dev
        - libxcb1-dev
        filesets:
            wanted:
            - etc/*
            - lib/*
            - usr/lib/x86_64-linux-gnu/*
            - usr/lib/*
            - share/icons/hicolor/256x256/apps/*
            - lib/x86_64-linux-gnu/* 
            - usr/lib/x86_64-linux-gnu/mesa/*
            - usr/lib/x86_64-linux-gnu/qt5/plugins 
        prime:
        - $wanted
